_wandb:
    value:
        cli_version: 0.21.4
        e:
            mmoiwb2fssvvqw08hjaghqag6zuych0h:
                args:
                    - -f
                    - /tmp/tmpzuax0wh4.json
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "195722883072"
                        used: "139350409216"
                executable: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/13-PregradoJulian/Federal Learning/infraestructura federada/Federal-Learning/.venv/bin/python
                git:
                    commit: 8a1c2f5846b4213a737c4efeba79565fc50456b6
                    remote: git@github.com:Ayax911/Federal-Learning.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c5b5be7b-8c3e-86ad-6240-79778baae0e8
                host: labmirp-Precision-5860-Tower
                memory:
                    total: "134269353984"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.39
                program: <python with no main file>
                python: CPython 3.12.8
                root: /media/imagenesmedicas/DATA1/01-ImagenesMedicas-US1/13-PregradoJulian/Federal Learning/infraestructura federada/Federal-Learning/runs/exp28_resnet50_radimagenet_mammobench_layer4_mlp03_ce_lr1e-4_img256_bs16_wandb
                startedAt: "2026-08-17T02:25:11.700629Z"
                writerId: mmoiwb2fssvvqw08hjaghqag6zuych0h
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
                - 62
            "4": 3.12.8
            "5": 0.21.4
            "8":
                - 13
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 16
block:
    value: 7
dropout:
    value: 0.3
exp_id:
    value: exp28
head:
    value: mlp
image_size:
    value: 256
loss:
    value: CrossEntropyLoss
lr:
    value: 0.0001
lr_backbone:
    value: 0.0001
num_epochs:
    value: 100
patience:
    value: 20
rotation_degrees:
    value: 7
seed:
    value: 42
unfreeze_idx:
    value:
        - 7
unfrozen:
    value: solo la última capa (layer4) descongelada
weight_decay:
    value: 0.0001
