defaults: base.yaml

name: test_synthetic
mode: federated

data:
  name: synthetic
  image_size: 64
  batch_size: 8
  grayscale: true
  num_classes: 2
  val_fraction: 0.2
  test_fraction: 0.2
  synthetic_num_samples: 200

model:
  name: resnet18
  pretrained: false
  in_channels: 1
  dropout: 0.2
  num_classes: 2

training:
  local_epochs: 1
  optimizer:
    name: adamw
    lr: 1.0e-4
    weight_decay: 1.0e-4
  loss:
    name: ce
    auto_class_weights: true

federated:
  num_clients: 2
  rounds: 3
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2
  accept_failures: false
  server_address: "0.0.0.0:8080"
  strategy:
    name: fedavg
